### ISSUE TITLE
403 causes panic

### ISSUE THREAD

**Issue by clburlison** [1dustindavis/gorilla#65]
This was 100% a permission issue on my end but a 403 download code shouldn't cause a panic in the code.

```ps1
PS C:\Users\Clayton Burlison\Desktop\cpe-chef-repo> C:\ProgramData\gorilla\bin\gorilla.exe -v
Retrieving manifest: unity_prd
Manifest Url: https://example.com/gorilla_repo/manifests/company_prd.yaml
panic: Unable to retrieve manifest:company_prdcompany_prd.yaml : Download status code: 403

goroutine 1 [running]:
log.Panic(0xc000067d40, 0x3, 0x3)
        /usr/local/go/src/log/log.go:326 +0xc7
github.com/1dustindavis/gorilla/pkg/gorillalog.Error(0xc000067d40, 0x3, 0x3)
        /ext-go/1/src/github.com/1dustindavis/gorilla/pkg/gorillalog/gorillalog.go:78 +0x5f
github.com/1dustindavis/gorilla/pkg/manifest.Get(0xc000067f68, 0x2, 0x2)
        /ext-go/1/src/github.com/1dustindavis/gorilla/pkg/manifest/manifest.go:68 +0x7b4
main.main()
        /ext-go/1/src/github.com/1dustindavis/gorilla/cmd/gorilla/main.go:25 +0xd0
```

**Comment by erikng** [comment]
Whatever does that double manifest name to come up should also be fixed. I saw that as well.

Thanks,
Erik Gomez
________________________________

**Comment by 1dustindavis** [comment]
Thanks for the issue!

This should be pretty easy to fix as we are getting the right error, we just aren’t exiting gracefully.
