### ISSUE TITLE
gorilla traces if one of the catalogs doesn't exist

### ISSUE THREAD

**Issue by erikng** [1dustindavis/gorilla#84]
Should you add a catalog that doesn't exist in a manifest, gorilla will trace with the following error:

```
C:\ProgramData\gorilla\bin\gorilla.exe
panic: Unable to retrieve catalog:somename.yaml : Download status code: 403

goroutine 1 [running]:
log.Panic(0xc000073dc8, 0x3, 0x3)
        /usr/local/go/src/log/log.go:326 +0xc7
github.com/1dustindavis/gorilla/pkg/gorillalog.Error(0xc000073dc8, 0x3, 0x3)
        /ext-go/1/src/github.com/1dustindavis/gorilla/pkg/gorillalog/gorillalog.go:78 +0x5f
github.com/1dustindavis/gorilla/pkg/catalog.Get(0xc000073f48)
        /ext-go/1/src/github.com/1dustindavis/gorilla/pkg/catalog/catalog.go:80 +0x2e4
main.main()
        /ext-go/1/src/github.com/1dustindavis/gorilla/cmd/gorilla/main.go:29 +0x185
PS C:\WINDOWS\system32> C:\ProgramData\gorilla\bin\gorilla.exe
panic: Unable to retrieve catalog:somename.yaml : Download status code: 403

goroutine 1 [running]:
log.Panic(0xc000073dc8, 0x3, 0x3)
        /usr/local/go/src/log/log.go:326 +0xc7
github.com/1dustindavis/gorilla/pkg/gorillalog.Error(0xc000073dc8, 0x3, 0x3)
        /ext-go/1/src/github.com/1dustindavis/gorilla/pkg/gorillalog/gorillalog.go:78 +0x5f
github.com/1dustindavis/gorilla/pkg/catalog.Get(0xc000073f48)
        /ext-go/1/src/github.com/1dustindavis/gorilla/pkg/catalog/catalog.go:80 +0x2e4
main.main()
        /ext-go/1/src/github.com/1dustindavis/gorilla/cmd/gorilla/main.go:29 +0x185
```

Instead of tracing, it should warn that the catalog cannot be found and continue on with the run.

**Comment by 1dustindavis** [comment]
This is resolved in the latest build
